version: '3'

services:
  varnish:
    container_name: a16t-cache
    image: varnish:stable
    ports:
      - "50000:80"  # Expose Varnish on port 80
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl:ro
    environment:
      - VARNISH_SIZE=2G  # Cache size
    command: -p default_ttl=3600 -p default_grace=3600