services:
  external:
    container_name: shopify-nexus
    # The name of the image that will be created when building this container
    image: shopify-nexus
    build:
      context: ./../
      dockerfile: ./.docker/Dockerfile
    user: "node"
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
      # Sets the timezone of the containers OS
      - TZ=Europe/Vilnius
    # Points to a file with the sensitive environment variables
    env_file:
      - ../.env
    restart: unless-stopped
    ports:
      - 51000:3000
  varnish:
    container_name: a16t-cache
    image: a16t-cache
    build:
      context: ./../packages/automatic-discount-cache
      dockerfile: ./.docker/Dockerfile
    ports:
      - "50000:80"    # Expose Varnish on port 80
      - "50001:3000"  # Expose Varnish on port 80
    volumes:
      - ../packages/automatic-discount-cache/production.vcl:/etc/varnish/default.vcl:ro
    environment:
      - VARNISH_SIZE=2G  # Cache size
    command: -p default_ttl=3600 -p default_grace=3600