services:
  shopify-nexus:
    container_name: shopify-nexus
    # The name of the image that will be created when building this container
    image: shopify-nexus-monorepo
    build:
      context: ./../
      dockerfile: ./.docker/Dockerfile
    user: "node"
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
      # Sets the timezone of the containers OS
      - TZ=Europe/Vilnius
    # Points to a file with the sensitive environment variables
    env_file:
      - ../.env
    restart: unless-stopped
    ports:
      - 51000:3000
    command: ["sh", "-c", "cd apps/shopify-nexus && node build/index.js"]
  
  auto-price-cache:
    container_name: auto-price-cache
    # The name of the image that will be created when building this container
    image: auto-price-cache-monorepo
    build:
      context: ./../
      dockerfile: ./.docker/Dockerfile
    user: "node"
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production
      # Sets the timezone of the containers OS
      - TZ=Europe/Vilnius
    # Points to a file with the sensitive environment variables
    env_file:
      - ../.env
    restart: unless-stopped
    ports:
      - 51001:3000
    volumes:
      # Persist logs directory
      - ../apps/auto-price-cache/logs:/app/apps/auto-price-cache/logs
      # Persist cache directory
      - ../apps/auto-price-cache/.cache:/app/apps/auto-price-cache/.cache
    command: ["sh", "-c", "cd apps/auto-price-cache && node build/index.js"]
  
  varnish:
    container_name: a16t-cache
    image: a16t-cache
    build:
      context: ./../apps/automatic-discount-cache
      dockerfile: ./.docker/Dockerfile
    ports:
      - "50000:80"    # Expose Varnish on port 80
      - "50001:3000"  # Expose Varnish on port 80
    volumes:
      - ../apps/automatic-discount-cache/production.vcl:/etc/varnish/default.vcl:ro
    environment:
      - VARNISH_SIZE=2G  # Cache size
    command: -p default_ttl=3600 -p default_grace=3600