name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/ci-bot/tko-monorepo
            git pull
            chmod +x ./.docker/deploy.sh
            ./.docker/deploy.sh
      - name: Clean up Docker
        run: |
          # Remove dangling images only (safer)
          docker image prune -f
